CREATE TABLE IF NOT EXISTS `tbl_chat` (
`ID` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
`timestamp` BIGINT NOT NULL,
`playername` TEXT NOT NULL,
`message` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `tbl_block` (
`ID` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
`timestamp` BIGINT NOT NULL,
`reason` TEXT NOT NULL,
`eventType` INTEGER NOT NULL,
`worldName` TEXT NOT NULL,
`blockX` INTEGER NOT NULL,
`blockY` INTEGER NOT NULL,
`blockZ` INTEGER NOT NULL,
`fromID` INTEGER NOT NULL,
`fromData` INTEGER NOT NULL,
`toID` INTEGER NOT NULL,
`toData` INTEGER NOT NULL
);